version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/Portal:/home/Portal
      - ./jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/sshpass:/usr/bin/sshpass
      - /usr/lib/jvm/:/usr/lib/jvm
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose

